### ISSUE TITLE
Fix behaviour of Missing Values

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#481]
# Todo

- [x] add as default of default `""^^cube:Undefined``
- [x] Replace with cube:Undefined in the case of sh:IRI somewhere in the pipelines
- [x] Fix `sh:in` to represent the necessary structure as defined in the rdf-cube-schema.

# Description
When trying to import the following CSV 
```
id,string
1,Hier wird
2,Zeile 3 ganz einfach
3,
4,nicht importiert
```
with identifier template `Observations/{id}` the following behavior is observed
- Pipeline reports success
- Line 3 is skipped
- if column "string" has a default value doesn't matter

I suggest that at least
- replacing blanks with a default value should enable import of line 3
- Instead of the line being skipped an error should be thrown

Technically imo simply not creating an observation could be a sufficient behavior as long as the column isn't used in the identifier template - depending on the needs of IXT of course.

<img src="https://user-images.githubusercontent.com/17119538/106428553-76a80a80-6469-11eb-918f-55ea5696805d.png" width="50%" height="50%" />

**Comment by danielmittag** [comment]
Update: I just checked the published cube and line 3 is actually present (english example)

```
DESCRIBE <https://environment.ld.admin.ch/foen/case-study-blanks/1/observation/3>

<https://environment.ld.admin.ch/foen/case-study-blanks/1/observation/2> a <http://ns.bergnet.org/cube/Observation> ;
   <http://ns.bergnet.org/cube/observedBy> <https://pipelines-integ.lindas.admin.ch/organization/bafu> ;
   <https://environment.ld.admin.ch/foen/case-study-blanks/id> "2" ;
   <https://environment.ld.admin.ch/foen/case-study-blanks/string> "simply isn't" .
```

```
DESCRIBE <https://environment.ld.admin.ch/foen/case-study-blanks/1/observation/3>

<https://environment.ld.admin.ch/foen/case-study-blanks/1/observation/3> a <http://ns.bergnet.org/cube/Observation> ;
   <http://ns.bergnet.org/cube/observedBy> <https://pipelines-integ.lindas.admin.ch/organization/bafu> ;
   <https://environment.ld.admin.ch/foen/case-study-blanks/id> "3" .
```

In this case we should make sure the data is returned by the query library / all sparql queries used

**Comment by danielmittag** [comment]
Update: I just created #521 which describes the same problem more accurately.

**Comment by l00mi** [comment]
@bergos what are the defined default value for blanks if not numeric?

**Comment by bergos** [comment]
If you want to say it's null, use NaN. For this case an empty string could make more sense. @ktk ?

**Comment by tpluscode** [comment]
Have you not defined it that `NaN` should only be used for numeric dimensions?

**Comment by ktk** [comment]
Yes I agree, NaN is only valid int he context of numbers.

**Comment by l00mi** [comment]
I want a decision on this this afternoon.. please read up on that to be prepared. Following problems I see:
If I interpret this https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes and also https://www.w3.org/TR/xmlschema11-2/#decimal this correctly:
* "NaN" as a value is only valid for xsd:float and xsd:double, in the cube curator we only alow xsd:integer and xsd:decimal. So do we not care and also use it for xsd:integer and xsd:decimal, or do we find another solution? 
* ""^xsd:string is okay for me to go as a solution for everything not numeric, that is the plan?

Finally we could also add the "missing" parts to the cube ontology based on https://webcache.googleusercontent.com/search?q=cache:qr9fcfkpnagJ:https://sdmx.org/wp-content/uploads/CL_OBS_STATUS_v1_0_2009.doc+&cd=2&hl=en&ct=clnk&gl=ch, this would cover for sure a good amount of use cases?

**Comment by ktk** [comment]
Approach
* Define a new IRI which can be used as datatype or named node
* In an observation we would use an empty literal with this particular datatype
* The SHACL shape needs to allow both types
* In a dimension with named nodes the IRI would be added to the list of possible named nodes

Result should be documented [here](https://github.com/zazuko/rdf-cube-schema/blob/master/best-practice.md#nullempty-values).

**Comment by ktk** [comment]
Example:

```turtle
# NamedNode Dimensions

<observation1> a cube:Observation;
  ex:namedNodeDimension cube:Undefined;

<observation2> a cube:Observation;
  ex:namedNodeDimension ex:realValue1;

<observation3> a cube:Observation;
  ex:namedNodeDimension ex:realValue2;

[
    sh:path ex:namedNodeDimension;
    sh:nodeKind sh:IRI;
    sh:in(cube:Undefined, ex:realValue1, ex:realValue2)
]


# Literals Dimensions

<observation2> a cube:Observation;
  ex:literalDimension ""^^cube:Undefined.

[
    sh:path ex:literalDimension;
    sh:nodeKind sh:Literal;
    sh:or([
        sh:datatype xsd:string
    ], [
        sh:datatype cube:Undefined
    ])
]
```
