### ISSUE TITLE
Add missing metadata for lindas.admin.ch/dataset

### ISSUE THREAD

**Issue by l00mi** [zazuko/cube-creator#730]
To properly show on https://int.lindas.admin.ch/datasets/ add missing fields defined here https://schema.ld.admin.ch/LindasDataset namely:

The missing information needs to be added to the "Organisation Profile":
* [x] SPARQL Endpoint and GUI -> PROFILE: should be in BAFU case environment.ld.admin.ch/query end enviroment.ld.admin.ch/sparql (#806)
* [x] Contact Point -> needs mirror values (#806)
* [x] [on hold] Link directly to Visualize.admin.ch with dataset selected. -> missing URI link dependent on https://github.com/visualize-admin/visualization-tool/issues/87

* [x] [@tpluscode] Link from void of domain e.g. https://environment.ld.admin.ch/.well-known/void equivalent to ISIL in https://culture.ld.admin.ch/.well-known/void (only for published cubes) (#804)

**Comment by martinmaillard** [comment]
About `contactPoint`, the current metadata uses `vcard:Organization`, but `LindasDataset` specifies that `contactPoint` must be either `schema:Organization` or `schema:Person`. And most of the other datasets point to an organization. I think we should maybe point to the BAFU organization instead of mirroring values from `dcat:contactPoint`?

**Comment by l00mi** [comment]
It is true that it is not clear if its a `schema:Person` or `schema:Organization`, but the background idea of contact Point is to have a tangible contact, so a Person would be best. We might need to discuss this with the customer.. but for now I propose to map vcard:name -> schema:name and vcard:email -> schema:email bot in a new object schema:Person.

**Comment by l00mi** [comment]
@l00mi find better property for SPARQL GUI instead of dcat:landinpage.

**Comment by tpluscode** [comment]
About `.well-known/void`, I don't think we actually have a base URI where to simply append such path.

I propose we make this an organisation profile property and link to it when publishing

**Comment by martinmaillard** [comment]
@l00mi Which property should I use for linking to visualize?
